---
# defaults file for sa_loki_promtail

loki_user:   loki
loki_group:  loki

loki_base_dir: /opt/loki_promtail
loki_dir: "{{ loki_base_dir }}"
loki_config_dir: /etc/loki_promtail
loki_promtail_version: "2.0.0"

loki_server_url: http://127.0.0.1:3100

promtail_additional_groups: adm

loki_dist_url: "https://github.com/grafana/loki/releases/download/v{{ loki_promtail_version }}/promtail-linux-arm64.zip"
loki_dist_location: "{{ loki_base_dir }}/promtail-linux-arm64.zip"
