---
- name: Create gempbot user
  user:
    name: gempbot
    shell: /bin/bash
    groups:
      - gempbot
    append: yes

- name: Install Router Service
  template:
    src: templates/service.j2
    dest: /etc/systemd/system/router.service