---

- name: Restart caddy
  systemd:
    daemon_reload: true
    name: caddy
    state: restarted

- name: Reload caddy
  systemd:
    name: caddy
    state: reloaded

- name: Restart gempbot
  systemd:
    daemon_reload: true
    name: gempbot
    state: restarted