name: Test and coverage

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - uses: dominikh/staticcheck-action@v1.2.0\
        with:
          install-go: false
      - name: Run coverage
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./internal/...
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)