name: Provision

on: 
  workflow_dispatch:

jobs:
  deploy:
      name: Provision
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Run ansible
          run: |
            touch .env
            echo "${{secrets.VAULT_PASSWORD}}" > ansible/.vaultpass
            export ANSIBLE_HOST_KEY_CHECKING=False
            make ansible
            make provision